version: '3'

services:
  broker:
    image: rabbitmq:3-management-alpine
    hostname: broker
    environment:
      - RABBITMQ_DEFAULT_USER=krolik
      - RABBITMQ_DEFAULT_PASS=karliczek
    ports:
      - 5672:5672
      - 15672:15672
